{% set name = "boinor" %}
{% set version = "0.19.0" %}
{% set python_min = "3.10" %}
{% set python_max = "3.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/boinor-{{ version }}.tar.gz
  sha256: b333feceb79ea190d5205735f664506b74a94241da096a7996ca5cf8ea88c280

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=3.4,<4
  run:
    - astropy-base >=6.1
    - astroquery >=0.3.9
    - czml3
    - jplephem
    - matplotlib-base !=3.0.1,>=2.0
    - numba >=0.61.0
    - numpy >=2.0.2
    - pandas
    - plotly <6,>=4.0
    - pyerfa
    - python >={{ python_min }},<{{ python_max }}
    - scipy >=1.4.0

test:
  imports:
    - boinor
    - boinor.constants
    - boinor.twobody
    - boinor.threebody
    - boinor.iod
    - boinor.frames
    - boinor.plotting
    - boinor.ephem
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/boinor/
  summary: Utilities and Python wrappers for Orbital Mechanics.
  dev_url: https://github.com/boinor/boinor
  license: MIT
  license_file: COPYING

extra:
  recipe-maintainers:
    - boinor
